### ISSUE TITLE
We need a restaurant NOW!

### ISSUE THREAD

**Issue by ewgalassi** [michaelguillen7/project_one#3]
### USER STORY
As a HUNGRY PERSON, I want to FIND A RESTAURANT MEETING MY SPECIFICATIONS without having to choose from a LIST OF CHOICES.

### Acceptance Criteria
 - [ ] Search criteria
 - [ ] Call Google Maps API and Zomato API to retrieve choices
 - [ ] Give back one choice
 - [ ] Be able to reject the choice and get another
 - [ ] Be able to make a reservation

**Comment by ImpunityJainne** [comment]
We did it!
